# Generated by Django 5.1.1 on 2024-09-24 00:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=accounts.models.avatar_upload_to),
        ),
    ]
