# Generated by Django 5.1.1 on 2024-09-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mean_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
